// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository_interface.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dimalewshin98-glitch/LTCalendar/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockRepositoryInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryInterfaceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepositoryInterface)(nil).Ping), ctx)
}

// CreateUser mocks base method.
func (m *MockRepositoryInterface) CreateUser(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryInterfaceMockRecorder) CreateUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateUser), ctx, userID)
}

// CreateMeeting mocks base method.
func (m *MockRepositoryInterface) CreateMeeting(ctx context.Context, meeting model.Meeting) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeeting", ctx, meeting)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeeting indicates an expected call of CreateMeeting.
func (mr *MockRepositoryInterfaceMockRecorder) CreateMeeting(ctx, meeting interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeeting", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateMeeting), ctx, meeting)
}

// UpdateMeeting mocks base method.
func (m *MockRepositoryInterface) UpdateMeeting(ctx context.Context, meeting model.Meeting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMeeting", ctx, meeting)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMeeting indicates an expected call of UpdateMeeting.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateMeeting(ctx, meeting interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMeeting", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateMeeting), ctx, meeting)
}

// UpdateMeetingStatus mocks base method.
func (m *MockRepositoryInterface) UpdateMeetingStatus(ctx context.Context, meetingID int, status model.ProcessingStatus, errorText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMeetingStatus", ctx, meetingID, status, errorText)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMeetingStatus indicates an expected call of UpdateMeetingStatus.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateMeetingStatus(ctx, meetingID, status, errorText interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMeetingStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateMeetingStatus), ctx, meetingID, status, errorText)
}

// GetMeeting mocks base method.
func (m *MockRepositoryInterface) GetMeeting(ctx context.Context, userID int, meetingID int) (model.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeeting", ctx, userID, meetingID)
	ret0, _ := ret[0].(model.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeeting indicates an expected call of GetMeeting.
func (mr *MockRepositoryInterfaceMockRecorder) GetMeeting(ctx, userID, meetingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeeting", reflect.TypeOf((*MockRepositoryInterface)(nil).GetMeeting), ctx, userID, meetingID)
}

// ListMeetings mocks base method.
func (m *MockRepositoryInterface) ListMeetings(ctx context.Context, userID int) ([]model.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMeetings", ctx, userID)
	ret0, _ := ret[0].([]model.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMeetings indicates an expected call of ListMeetings.
func (mr *MockRepositoryInterfaceMockRecorder) ListMeetings(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMeetings", reflect.TypeOf((*MockRepositoryInterface)(nil).ListMeetings), ctx, userID)
}

// FindMeetings mocks base method.
func (m *MockRepositoryInterface) FindMeetings(ctx context.Context, userID int, keyword string) ([]model.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMeetings", ctx, userID, keyword)
	ret0, _ := ret[0].([]model.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMeetings indicates an expected call of FindMeetings.
func (mr *MockRepositoryInterfaceMockRecorder) FindMeetings(ctx, userID, keyword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMeetings", reflect.TypeOf((*MockRepositoryInterface)(nil).FindMeetings), ctx, userID, keyword)
}

// DeleteMeeting mocks base method.
func (m *MockRepositoryInterface) DeleteMeeting(ctx context.Context, userID int, meetingID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMeeting", ctx, userID, meetingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMeeting indicates an expected call of DeleteMeeting.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteMeeting(ctx, userID, meetingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMeeting", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteMeeting), ctx, userID, meetingID)
}
